use_frameworks!

target 'MCCommonMacroDefine_Example' do
  pod 'MCCommonMacroDefine', :path => '../'

  target 'MCCommonMacroDefine_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
